name: Go

on:
    push:

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              if: success()
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15.x
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Calc coverage
              run: |
                  export PATH=$PATH:$(go env GOPATH)/bin
                  cd pagination
                  go mod vendor
                  go test -v -coverpkg=./ -coverprofile=../coverage.out ./... -count=1
            - name: Convert coverage to lcov
              uses: jandelgado/gcov2lcov-action@v1.0.0
              with:
                  infile: coverage.out
                  outfile: coverage.lcov
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: coverage.lcov
